<?php

require __DIR__ . "/../model/class.php";

$concordeManager = new ConcordeManager();

// Récupérer les données depuis la base de données
$categories = $concordeManager->getAllCategories();
$salons = $concordeManager->getAllSalons();

$chosensalonID = isset($_GET['salonID']) ? $_GET['salonID'] : null;

// Poster un message dans un salon

$ALLMsg = [];
if (isset($_POST['messageText'])) {
    $messageText = $_POST['messageText'];
    $concordeManager->postMessage($messageText, $chosensalonID);
}

// Récupérer les messages du salon
if ($chosensalonID !== null) {

    $ALLMsg = $concordeManager->getMessages($chosensalonID);
}
?>




<main>
    <link rel="stylesheet" href="css/style.css">
    <aside id="category">
        <?php foreach ($categories as $category) { ?>
            <h2><?php echo $category['nom']; ?></h2>
            <?php foreach ($salons as $salon) { ?>
                <?php if ($salon['category_id'] == $category['id']) { ?>
                    <form method="GET" name="<?php echo $salon['nom'] ?? $salon['id']; ?>">
                        <button type="submit" name="salonID" value="<?php echo $salon['id']; ?>">
                            <?php echo $salon['nom']; ?>
                        </button>
                    </form>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </aside>

    <div id="ReadMsg" style="
     position: absolute;
    bottom:4vh;
    left: 41vh;
    width: 100%;
    background-color: white;
    padding: 10px;

    width: 100%;
    height:96vh;
    padding: 10px;
    box-sizing: border-box;
    border: 3px solid rgb(119, 16, 16);
    font-size: 16px;
    outline: none;
    background-color: rgb(0, 0, 0);
    color: aliceblue;
    
    
    ">
        <ul>
            <?php foreach ($ALLMsg as $row) { ?>
                <li><?php echo $row["texte"]; ?></li>
            <?php } ?>
        </ul>
    </div>


    <!-- Poster un message dans un salon -->
    <form action="" method="post" id="TextArea" style="
     position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    background-color: white;
    padding: 10px;

    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    border: 3px solid rgb(119, 16, 16);
    font-size: 16px;
    outline: none;
    background-color: rgb(0, 0, 0);
    color: aliceblue;
    
    
    ">
        <input type="text" name="messageText" placeholder="Message" style="
        
        width: 90%;
          height: auto;">
        <button type="submit">Poster Message</button>
    </form>

</main>